"""Extrase bancare: tranzactiile si legatura lor cu facturile

Trei tabele, si al treilea este cel care conteaza. `transaction_matches` are
tabel propriu — nu o coloana `document_id` pe tranzactie — pentru ca realitatea
unui cabinet nu este unu-la-unu: o plata inchide trei facturi deodata, o factura
se plateste in doua transe, se plateste mai mult (avans) sau mai putin (rest).
O coloana ar fi acoperit un caz din cinci.

Suma sta pe legatura, nu pe tranzactie: cat din plata asta a mers pe factura
aceea. Fara ea, „platit partial" nu se poate scrie deloc.

Ca la migrarea precedenta, operatiile sunt tinute de mana. `--autogenerate` a
propus 187, dintre care peste 150 „repara" indexuri de expresie si `server_default`
uri care nu au nimic in neregula — vezi motivul intreg in migrarea
`49d20fa1d6cc`.

Revision ID: c9334e45b970
Revises: 49d20fa1d6cc
Create Date: 2026-09-07 22:31:44.627347
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c9334e45b970"
down_revision: str | None = "49d20fa1d6cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_statements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("bank_name", sa.String(length=128), nullable=True),
        sa.Column("iban", sa.String(length=34), nullable=True),
        sa.Column("statement_number", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("closing_balance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imported_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_bank_statements_period_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_bank_statements_client_id_clients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_bank_statements_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["imported_by_id"],
            ["users.id"],
            name=op.f("fk_bank_statements_imported_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_bank_statements_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_statements")),
        sa.UniqueConstraint(
            "organization_id",
            "iban",
            "period_start",
            "period_end",
            "statement_number",
            name="uq_bank_statements_identity",
        ),
    )
    op.create_index(
        "ix_bank_statements_organization_id_client_id",
        "bank_statements",
        ["organization_id", "client_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_statements_period_start", "bank_statements", ["period_start"], unique=False
    )
    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("statement_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("direction", sa.String(8), nullable=False),
        sa.Column("counterparty_name", sa.String(length=255), nullable=True),
        sa.Column("counterparty_iban", sa.String(length=34), nullable=True),
        sa.Column("reference", sa.String(length=255), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('DEBIT', 'CREDIT')", name=op.f("ck_bank_transactions_direction")
        ),
        sa.CheckConstraint(
            "status IN ('UNMATCHED', 'SUGGESTED', 'MATCHED', 'IGNORED', 'NEEDS_REVIEW')",
            name=op.f("ck_bank_transactions_status"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_bank_transactions_amount_not_zero")),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_bank_transactions_client_id_clients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_bank_transactions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["bank_statements.id"],
            name=op.f("fk_bank_transactions_statement_id_bank_statements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_transactions")),
        sa.UniqueConstraint("statement_id", "position", name="uq_bank_transactions_position"),
    )
    op.create_index(
        "ix_bank_transactions_amount",
        "bank_transactions",
        ["organization_id", "amount"],
        unique=False,
    )
    op.create_index(
        "ix_bank_transactions_booking_date", "bank_transactions", ["booking_date"], unique=False
    )
    op.create_index(
        "ix_bank_transactions_client_id", "bank_transactions", ["client_id"], unique=False
    )
    op.create_index(
        "ix_bank_transactions_organization_id_status",
        "bank_transactions",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "transaction_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasons", sa.String(length=512), nullable=True),
        sa.Column("confirmed_by_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transaction_matches_amount_positive")),
        sa.ForeignKeyConstraint(
            ["confirmed_by_id"],
            ["users.id"],
            name=op.f("fk_transaction_matches_confirmed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_transaction_matches_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["bank_transactions.id"],
            name=op.f("fk_transaction_matches_transaction_id_bank_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_matches")),
        sa.UniqueConstraint("transaction_id", "document_id", name="uq_transaction_matches_pair"),
    )
    op.create_index(
        "ix_transaction_matches_document_id", "transaction_matches", ["document_id"], unique=False
    )


def downgrade() -> None:
    op.drop_table("transaction_matches")
    op.drop_table("bank_transactions")
    op.drop_table("bank_statements")
